[package]
name = "post_mint_reveal_nft_custom"
version = "0.0.0"
upgrade_policy = "compatible"

[dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }
AptosStdlib = { local = "../../framework/aptos-stdlib" }
AptosToken = { local = "../../framework/aptos-token" }
DataStructure = { local = "../data_structures" }

[addresses]
source_addr = "_"